# Generated by Django 4.2 on 2023-04-20 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_person_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
