# Generated by Django 4.2 on 2023-04-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
