# Generated by Django 4.2 on 2023-04-21 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='test',
        ),
    ]
